config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  resources  :posts
  root to: 'pages#home'


  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format", to: "pages#robots"

  constraints(host: /^(?!www\.)/i) do
  get '(*any)' => redirect { |params, request|
    URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
  }
    end
  #match "/old_path_to_posts/:id", to: redirect("/posts/%{id}s")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
      user ||= User.new # guest user (not logged in)
       if user.present?
         can :manage, :all
       else
         can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]
    has_one_attached :photo
    has_many_attached :photos

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_server_error
    render status: 500
  end

end

app/controllers/pages_controller.rb
require 'date'

class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :home, :robots, :date]

  def home
    @posts = Post.all
  end

  def date
    @date = Time.now
  end

  def robots
    respond_to :text
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, :only => [:create, :new, :update, :delete]
    load_and_authorize_resource
    add_breadcrumb "Work", :posts_path
      def index
        @posts = Post.all
      end

      def show
        @posts = Post.friendly.find(params[:id])
        add_breadcrumb @posts, post_path(@posts)
      end
      def new
        @post = Post.new
      end

      def create
        @post = Post.new(post_params)
         if @post.save
       redirect_to root_path
        end
      end


      def edit
        @post = Post.find(params[:id])
      end

      def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to post_path
      end

      def destroy
        @post = Post.find(params[:id])
        if @post.destroy
       redirect_to root_path
        end
      end

      private


      def post_params
          params.require(:post).permit(:id, :link ,:description, :name, :category ,:photo, photos: [])
      end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  skip_before_action :authenticate_user!
  layout :false
  before_action :init_sitemap

  def index
    @posts = Post.all
  end

  private

  def init_sitemap
    headers['Content-Type'] = 'application/xml'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <%= canonical_tag -%>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title>Noirfuture</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;600;700;800&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
</head>

<body id="main">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/349e7af2d0.js" crossorigin="anonymous"></script>
    <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>



</body>

</html>

app/views/layouts/application.html.slim
  ul.breadcrumb itemscope="" itemtype="http://schema.org/BreadcrumbList"
    = render_breadcrumbs tag: 'li', separator: '',
  builder: Breadcrumbs::Builders::StructuredDataBreadcrumbsBuilder

app/views/pages/home.html.erb
<div class="grid">
    <% @posts.shuffle.each do |post|%>

    <div class="item" style="background-image: url('<%= cl_image_path post.photo.key, crop: :scale %>')">
        <%= link_to 'POST', post_path(post)  %>



        <div class="card-noirfuture">
            <div class='description'>
                <%= post.name.upcase %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/pages/robots.text.slim
- if Rails.env == "production"
  = "User-Agent: *\n"
  = "Disallow: \n"
- else
  = "User-Agent: *\n"
  = "Noindex: /\n"

= "\nSitemap: http://noirfuture.world/sitemap.xml"

app/views/posts/_form.html.erb
<div class="col-3 d-flex justify-content-center mx-auto flex-column mt-5">
    <%= simple_form_for(post) do |f| %>
    <%= f.input :photo, label: 'Photo de couverture' ,as: :file %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :name, label: 'Nom' %>
    <%= f.input :description, as: :text  %>
    <%= f.input :category, label: 'Catégorie' %>
    <%= f.submit  class: "btn btn-primary d-flex justify-center", style: 'width: 100%', label: 'Créer un post'%>
    <% end %>
    <!-- <button id="upload_widget" class="cloudinary-button">Upload files</button> -->
</div>

<!-- label_html: { class: 'cloudinary-button' }, label_html: { id: 'upload_widget' } -->

app/views/posts/_post_modal.html.erb
<div id="post-modal" class="modal fade" role="dialog">
     <div class="modal-dialog modal-lg">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal">&times;</button>
         </div>

         <div>
 <% @posts.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
         </div>
       </div>
     </div>
</div>

app/views/posts/edit.html.erb
<h1 class='text-center'>Editing Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', root_path %>

app/views/posts/index.html.erb
<h1>salut</h1>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% content_for :meta_title, "#{@posts.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @posts.description %>
<div class="container mt-5">
    <% if user_signed_in? %>
    <h2 class="text-center postname">
        <%= @post.name %>
        <%= link_to post_path,
            method: :delete,
            data: { confirm: "Supprimer ce post ?" }  do %>
        <i class="fas fa-trash-alt" style="font-size: 20px;"></i>
        <% end %>
         <%= link_to edit_post_path do %>
        <i class="fas fa-pen" style="font-size: 20px;"></i>
        <% end %>
    </h2>
    <% else  %>
    <h2 class="text-center postname">
        <%= @post.name %>
    </h2>
    <% end %>
    <h3 class="text-center category">
        <%= @post.category %>
    </h3>
    <img class='cover' src="<%= cl_image_path @post.photo.key, class: :cover, crop: :crop %> " alt="">
    <div class="row p-5">
        <div style="margin-left: 8.33333333%" class="col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 client">
            <h3>DESCRIPTION</h3>
            <div class="division"></div>
            <p class='grey-description'>
                <%= @post.description %>
            </p>
        </div>
    </div>
    <div class='contenu'>
        <% @post.photos.each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.haml
%article[post]
  = link_to "/posts/#{post.id}", :itemprop => "url" do
    %h3[:name]>= post.title
  .post_body[:articleBody]= post.body.html_safe
  = time_tag(post.created_at, :itemprop => "datePublished")

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div id="mySidebar" class="sidebar">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
                <a target="_blank" href="https://www.behance.net/noirfuturestudio">BEHANCE</a>
                <a target="_blank" href="https://www.instagram.com/noirfuturestudio">INSTAGRAM</a>
                <a target="_blank" href="https://noirfuture.bigcartel.com/">BIGCARTEL</a>


                <%= mail_to "contact@noirfuturestudio.com" do %>
                CONTACT
                <% end %>
            </div>
            <div class="col-xs-2 col-sm-2 col-md-3 col-lg-3">
                <button class="openbtn">☰</button>
                <div class="leftpart">
                    <a target="_blank" href="https://www.behance.net/noirfuturestudio">BEHANCE</a>
                    <a target="_blank" href="https://www.instagram.com/noirfuturestudio">INSTAGRAM</a>
                    <a target="_blank" href="https://noirfuture.bigcartel.com/">BIGCARTEL</a>




                </div>
            </div>
            <div class="middle col-xs-8 col-sm-8 col-md-6 col-lg-6">
                <a href="/">
                    <%= image_tag ('logo1.png'), id: 'noirfuture', class: 'noirfuture' %>
                </a>
                <!--
        <div class='row phrase'>Bienvenu sur notre site</div>
        <div class='row date'> Wed / 16.09.20, 11:33:07 AM
MEXICO CITY </div>
-->
            </div>
            <div class="col-xs-2 col-sm-2 col-md-3 col-lg-3">
                <div class="rightpart">
                    <% if user_signed_in? %>
                    <a href="/posts/new" class="btn btn-noirfuture">Ajouter un post</a>
                    </button>
                    <% else %>
                    <a href="/users/sign_in">LOGIN</a>
                    <%= mail_to "contact@noirfuturestudio.com" do %>
                    CONTACT
                    <% end %>
                    <a href="" id=date>
                        <%= Time.now %></a>
                    <% end %>
                </div>
            </div>
        </nav>
    </div>
</header>